<?php

/**
 *
 * NOTICE OF LICENSE
 *
 * @category   Sp
 * @package    Sp_Productrelater
 */

?>
<?php 
    $colDataWithRelated = false;
    $colDataWithCrossSell = false;
    $colDataWithUpSell = false;
    $numColumns = sizeof($this->getColumns()); 
?>

<?php if($this->getCollection()): ?>

    <?php if($this->canDisplayContainer()): ?>
        <?php if($this->getGridHeader()): ?>
        <div class="content-header">
            <table cellspacing="0">
                <tr>
                    <td style="width:50%;"><h2><?php echo $this->getGridHeader(); ?></h2></td>
                </tr>
            </table>
        </div>
        <?php endif ?>

        <div id="<?php echo $this->getId() ?>">
    <?php else: ?>
        <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <?php endif; ?>

    <?php if($this->getPagerVisibility() || $this->getFilterVisibility()): ?>
        <table cellspacing="0" class="actions">
            <tr>
            <?php if($this->getPagerVisibility()): ?>
                <td class="pager">
                <?php echo $this->__('Page') ?>

                <?php $_curPage  = $this->getCollection()->getCurPage() ?>
                <?php $_lastPage = $this->getCollection()->getLastPageNumber() ?>

                <?php if($_curPage>1): ?>
                    <a href="#" title="<?php echo $this->__('Previous page') ?>" onclick="<?php echo $this->getId() ?>JsObjectIKSProductrelater.setPage('<?php echo ($_curPage-1) ?>');return false;"><img src="<?php echo $this->getSkinUrl('images/pager_arrow_left.gif') ?>" alt="Go to Previous page" class="arrow"/></a>
                <?php else: ?>
                    <img src="<?php echo $this->getSkinUrl('images/pager_arrow_left_off.gif') ?>" alt="Go to Previous page" class="arrow"/>
                <?php endif; ?>

                <input type="text" name="<?php echo $this->getVarNamePage() ?>" value="<?php echo $_curPage ?>" class="input-text page" onkeypress="<?php echo $this->getId() ?>JsObjectIKSProductrelater.inputPage(event, '<?php echo $_lastPage ?>')"/>

                <?php if($_curPage < $_lastPage): ?>
                    <a href="#" title="<?php echo $this->__('Next page') ?>" onclick="<?php echo $this->getId() ?>JsObjectIKSProductrelater.setPage('<?php echo ($_curPage+1) ?>');return false;"><img src="<?php echo $this->getSkinUrl('images/pager_arrow_right.gif') ?>" alt="Go to Next page" class="arrow"/></a>
                <?php else: ?>
                    <img src="<?php echo $this->getSkinUrl('images/pager_arrow_right_off.gif') ?>" alt="Go to Previous page" class="arrow"/>
                <?php endif; ?>
                <?php echo $this->__('of %s pages', $this->getCollection()->getLastPageNumber()) ?>
                <span class="separator">|</span>
                <?php echo $this->__('View') ?>
                <select name="<?php echo $this->getVarNameLimit() ?>" onchange="<?php echo $this->getId() ?>JsObjectIKSProductrelater.loadByElement(this)">
                    <option value="20"<?php if($this->getCollection()->getPageSize()==20): ?> selected="selected"<?php endif; ?>>20</option>
                    <option value="30"<?php if($this->getCollection()->getPageSize()==30): ?> selected="selected"<?php endif; ?>>30</option>
                    <option value="50"<?php if($this->getCollection()->getPageSize()==50): ?> selected="selected"<?php endif; ?>>50</option>
                    <option value="100"<?php if($this->getCollection()->getPageSize()==100): ?> selected="selected"<?php endif; ?>>100</option>
                    <option value="200"<?php if($this->getCollection()->getPageSize()==200): ?> selected="selected"<?php endif; ?>>200</option>
                </select>
                <?php echo $this->__('per page') ?><span class="separator">|</span>
                <?php echo $this->__('Total %d records found', $this->getCollection()->getSize()) ?>
                <span id="<?php echo $this->getHtmlId() ?>-total-count" class="no-display"><?php echo $this->getCollection()->getSize() ?></span>

                <?php if($this->getRssLists()): ?>
                    <?php foreach ($this->getRssLists() as $_rss): ?>
                        <span class="separator">|</span><a href="<?php echo $_rss->getUrl() ?>" class="link-feed"><?php echo $_rss->getLabel() ?></a>
                    <?php endforeach ?>
                <?php endif; ?>
            </td>
        <?php endif ?>
            <td class="filter-actions a-right">
                <?php echo $this->getMainButtonsHtml() ?>
            </td>
            
            </tr>
        </table>
    <?php endif; ?>
            
    <?php if($this->getMassactionBlock()->isAvailable()): ?>
        <?php echo $this->getMassactionBlockHtml() ?>
    <?php endif ?>
            
    <script type="text/javascript">
        this.massUpdateProducts = '<?php echo $this->getUrl('*/*/massUpdateProducts')?>';
    </script>
            
<form method="post" action="" id="editData">
    <div class="grid">
	<div class="hor-scroll">
	<table cellspacing="0" class="data" id="<?php echo $this->getId() ?>_table">
	    <?php foreach ($this->getColumns() as $_column): ?>
            <?php
                $colData = $_column->getData();
                if(isset($colData['index']))
                {
                    if($colData['index'] == 'product_qtys')
                        $colDataWithRelated = true;
                }
            ?>
            
	    <col <?php echo $_column->getHtmlProperty() ?> />
	    <?php endforeach; ?>
	    <?php if ($this->getHeadersVisibility() || $this->getFilterVisibility()): ?>
	        <thead>
	            <?php if ($this->getHeadersVisibility()): ?>
	                <tr class="headings">
	                <?php foreach ($this->getColumns() as $_column): ?>
	                    <th<?php echo $_column->getHeaderHtmlProperty() ?>><span class="nobr"><?php echo $_column->getHeaderHtml() ?></span></th>
	                <?php endforeach; ?>
	                </tr>
	            <?php endif; ?>
	            <?php if ($this->getFilterVisibility()): ?>
	                <tr class="filter">
	                <?php $i=0;foreach ($this->getColumns() as $_column): ?>
	                    <th<?php echo $_column->getHeaderHtmlProperty() ?>><?php echo $_column->getFilterHtml() ?></th>
	                <?php endforeach; ?>
	                </tr>
	            <?php endif ?>
	        </thead>
	    <?php endif; ?>
	    <?php if ($this->getCountTotals()): ?>
	        <tfoot>
	            <tr>
	            <?php foreach ($this->getColumns() as $_column): ?>
	                <th class="<?php echo $_column->getCssProperty() ?>"><?php echo $_column->getRowField($_column->getGrid()->getTotals()) ?>&nbsp;</th>
	            <?php endforeach; ?>
	            </tr>
	         </tfoot>
	    <?php endif; ?>
	    <tbody>
	    <?php if (($this->getCollection()->getSize()>0) && (!$this->getIsCollapsed())): ?>
	    <?php foreach ($this->getCollection() as $_index=>$_item): ?>
                <?php
                if($colDataWithRelated && $_item->getTypeId() == 'simple')
                {
                    $qty = (int)Mage::getModel('cataloginventory/stock_item')->loadByProduct($_item)->getQty();
                    $_item->setData('product_qtys', $qty);
                }
                ?>
                
	        <tr title="<?php echo $this->getRowUrl($_item) ?>"<?php if ($_class = $this->getRowClass($_item)):?> class="<?php echo $_class; ?>"<?php endif;?> id="product<?php echo $_item->getData('entity_id');?>">
	        <?php $i=0;foreach ($this->getColumns() as $_column): ?>
	            <td class="<?php echo $_column->getCssProperty() ?> <?php echo ++$i==$numColumns?'last':'' ?>"><?php echo (($_html = $_column->getRowField($_item)) != '' ? $_html : '&nbsp;') ?></td>
	        <?php endforeach; ?>
	        </tr>
	    <?php endforeach; ?>
	    <?php elseif ($this->getEmptyText()): ?>
	    	<tr>
                    <td class="empty-text <?php echo $this->getEmptyTextClass() ?>" colspan="100"><?php echo $this->getEmptyText() ?></td>
	    	</tr>
	    <?php endif; ?>
	    </tbody>
	</table>
	</div>
    </div>
        
    </form>
<?php if($this->canDisplayContainer()): ?>
</div>

<script type="text/javascript">
//<![CDATA[
    <?php echo $this->getJsObjectName() ?> = new varienGridIKSProductRelater('<?php echo $this->getId() ?>', '<?php echo $this->getGridUrl() ?>', '<?php echo $this->getVarNamePage() ?>', '<?php echo $this->getVarNameSort() ?>', '<?php echo $this->getVarNameDir() ?>', '<?php echo $this->getVarNameFilter() ?>');
    <?php echo $this->getJsObjectName() ?>.useAjax = '<?php echo $this->getUseAjax() ?>';
    <?php if($this->getRowClickCallback()): ?>
        <?php echo $this->getJsObjectName() ?>.rowClickCallback = <?php echo $this->getRowClickCallback() ?>;
    <?php endif; ?>
    <?php if($this->getCheckboxCheckCallback()): ?>
        <?php echo $this->getJsObjectName() ?>.checkboxCheckCallback = <?php echo $this->getCheckboxCheckCallback() ?>;
    <?php endif; ?>
    <?php if($this->getRowInitCallback()): ?>
        <?php echo $this->getJsObjectName() ?>.initRowCallback = <?php echo $this->getRowInitCallback() ?>;
        <?php echo $this->getJsObjectName() ?>.rows.each(function(row){<?php echo $this->getRowInitCallback() ?>(<?php echo $this->getJsObjectName() ?>, row)});
    <?php endif; ?>
    <?php if($this->getMassactionBlock()->isAvailable()): ?>
        <?php echo $this->getMassactionBlock()->getJavaScript() ?>
    <?php endif ?>
//]]>
</script>
<?php endif; ?>
<?php endif ?>